### ISSUE TITLE
can't install crossover from aur

### ISSUE THREAD

**Issue by yswtrue** [Vanilla-OS/apx#132] opened 2023-02-18 19:20 UTC
```shell
apx --aur install crossover -f
 -> Could not find all required packages:
        lib32-libsm (Wanted by: crossover)
        lib32-freetype2 (Wanted by: crossover)
        lib32-libpng (Wanted by: crossover)
        lib32-lcms2 (Wanted by: crossover)
        lib32-libgl (Wanted by: crossover)
        lib32-libice (Wanted by: crossover)
        lib32-libx11 (Wanted by: crossover)
        lib32-libxext (Wanted by: crossover)
        lib32-libxi (Wanted by: crossover)
        lib32-zlib (Wanted by: crossover)
        lib32-libxcursor (Wanted by: crossover)
        lib32-libxrandr (Wanted by: crossover)
        lib32-glu (Wanted by: crossover)
Error: exit status 1
Usage:
  apx install <packages> [flags]

Examples:
apx install htop git
apx install --sideload /path/to/file.deb

Flags:
  -y, --assume-yes   Proceed without manual confirmation.
  -f, --fix-broken   Fix broken deps before installing.
  -h, --help         help for install
      --no-export    Do not export a desktop entry after the installation.
      --sideload     Install a package from a local file.

Global Flags:
      --apk           Install packages from the Alpine repository.
      --apt           Install packages from the Ubuntu repository.
      --aur           Install packages from the AUR (Arch User Repository).
      --dnf           Install packages from the Fedora's DNF (Dandified YUM) repository.
  -n, --name string   Create or use custom container with this name.
```

**Comment by matbme** [comment] 2023-02-25 21:34
See https://wiki.archlinux.org/title/Official_repositories#multilib

**Comment by mirkobrombin** [comment] 2023-02-25 21:49
closing since not a bug in apx, feel free to add more comments

**Closed by mirkobrombin** 2023-02-25 21:49 UTC
