### ISSUE TITLE
[Feature] a way to delete containers

### ISSUE THREAD

**Issue by Heus-Sueh** [Vanilla-OS/apx#87] opened 2023-01-25 14:49 UTC
I think the vanilla control center could have a button "delete container" on the same side as "enter the shell" button
![Screenshot from 2023-01-25 11-43-28](https://user-images.githubusercontent.com/98482469/214593847-dbe0bbee-a8af-472b-beb3-fcf9b8dff5be.png)

**Comment by mirkobrombin** [comment] 2023-01-25 15:11
Duplicate of https://github.com/Vanilla-OS/vanilla-control-center/issues/90

also wrong repository

**Closed by mirkobrombin** 2023-01-25 15:11 UTC
